import { ToastContainer } from "react-toastify";
import Nav from "./components/Nav";
import SideBar from "./components/SideBar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased w-screen h-screen gap-2 flex overflow-hidden bg-[#121212] p-2.5`}
      >
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />
        <SideBar />
        <div className="sm:w-[75vw] fixed top-2.5 right-1 w-full  h-full ">
          <Nav />
          <div className="w-full h-full  mt-2 scrollbar   overflow-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
